CREATE TABLE Member (
    id INTEGER AUTO_INCREMENT NOT NULL,
    membership VARCHAR(50) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    age VARCHAR(15) NOT NULL,
    telf VARCHAR(15) NOT NULL,
    email VARCHAR(50) NOT NULL
);